# Type  Path                         Mode  User  Group  Age  Argument
# Ensure the parent dir exists and is owned by sddm
d       /var/lib/sddm                0750  sddm  sddm   -    -

# Ensure the themes dir is accessible to you for management
# 0775 allows the 'sddm' group (which you can join) to write to it
d       /var/lib/sddm/themes        0775  sddm  sddm   -    -
